/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/novelas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Novelas */
        get: operations["novelas_novelas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado */
        get: operations["estado_novelas__slug__estado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_novelas__slug__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/escaleta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Escaleta */
        get: operations["escaleta_novelas__slug__escaleta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkpoint */
        get: operations["checkpoint_novelas__slug__checkpoint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_novelas__slug__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/runs/{run_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log
         * @description El tramo de `harness.log` desde el byte `desde`, que el panel encadena con `hasta` (D48).
         *     Un run sin log todavía responde un tramo vacío: solo existe entre el manifiesto y la primera
         *     línea.
         */
        get: operations["log_novelas__slug__runs__run_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manifiesto */
        get: operations["manifiesto_novelas__slug__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/portada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portada */
        get: operations["portada_novelas__slug__portada_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/metricas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metricas */
        get: operations["metricas_novelas__slug__metricas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/capitulos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indice */
        get: operations["indice_novelas__slug__capitulos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/capitulos/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capitulo */
        get: operations["capitulo_novelas__slug__capitulos__n__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/libro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Libro
         * @description Portada, índice y ficha de la lectura web; lo mismo que el PDF (docs/lectura-web.md).
         */
        get: operations["libro_novelas__slug__libro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novelas/{slug}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pdf
         * @description El libro de regalo en PDF con los capítulos cerrados, para descargar (spec 0015). El título
         *     es el que muestra el panel: el slug con espacios, mientras la novela no tenga uno propio.
         */
        get: operations["pdf_novelas__slug__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lanzamientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lanzamientos */
        get: operations["lanzamientos_lanzamientos_get"];
        put?: never;
        /** Crear */
        post: operations["crear_lanzamientos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lanzamientos/{slug}/reanudar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reanudar */
        post: operations["reanudar_lanzamientos__slug__reanudar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lanzamientos/{slug}/detener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detener
         * @description Para tras el capítulo en curso: matar una sesión a medias dejaría el capítulo sin cerrar.
         */
        post: operations["detener_lanzamientos__slug__detener_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lanzamientos/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lanzamiento */
        get: operations["lanzamiento_lanzamientos__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Acto */
        Acto: {
            /** Numero */
            numero: number;
            /** Funcion Dramatica */
            funcion_dramatica: string;
            /** Capitulos */
            capitulos: number[];
        };
        /**
         * Agente
         * @enum {string}
         */
        Agente: "arquitecto" | "trazador" | "escritor" | "continuista" | "editor-estilo" | "lector-suspense" | "cronista" | "juez";
        /**
         * Checkpoint
         * @description `checkpoints/NN.json` y `latest.json`: cursor, versiones y run_id, no la base (RF-20).
         *     `capitulos_sha256` es el sello de los capítulos cerrados hasta N (RF-35).
         */
        Checkpoint: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Capitulo */
            capitulo: number;
            cursor: components["schemas"]["Cursor"];
            /** Run Id */
            run_id: string;
            /** Version Canon */
            version_canon: string;
            /** Version Plan */
            version_plan: string;
            /** Capitulos Sha256 */
            capitulos_sha256: {
                [key: string]: string;
            };
        };
        /** Config */
        Config: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Idea Semilla */
            idea_semilla: string;
            parametros_obra: components["schemas"]["ParametrosObra"];
            parametros_sistema: components["schemas"]["ParametrosSistema"];
        };
        /** Consumo */
        Consumo: {
            /** Llamadas */
            llamadas: number;
            /** Tokens Entrada */
            tokens_entrada: number;
            /** Tokens Salida */
            tokens_salida: number;
            /** Tokens Cache Lectura */
            tokens_cache_lectura: number;
            /** Coste Usd */
            coste_usd: number;
            /** Latencia Media Llamada S */
            latencia_media_llamada_s: number;
        };
        /** ConsumoDePaso */
        ConsumoDePaso: {
            /** Llamadas */
            llamadas: number;
            /** Tokens Entrada */
            tokens_entrada: number;
            /** Tokens Salida */
            tokens_salida: number;
            /** Tokens Cache Lectura */
            tokens_cache_lectura: number;
            /** Coste Usd */
            coste_usd: number;
            /** Latencia Media Llamada S */
            latencia_media_llamada_s: number;
            /** Paso */
            paso: string;
            /** Latencia S */
            latencia_s: number;
            /** Roles */
            roles: {
                [key: string]: components["schemas"]["Consumo"];
            };
        };
        /** Cursor */
        Cursor: {
            /** Capitulo */
            capitulo: number;
            /**
             * Fase
             * @enum {string}
             */
            fase: "escritura" | "revision" | "registro" | "cerrado";
            /** Ultimo Paso */
            ultimo_paso: ("briefing" | "escritor" | "validar" | "continuista" | "editor-estilo" | "lector-suspense" | "cronista" | "aplicar-delta" | "checkpoint") | null;
            /** Intento */
            intento: number;
        };
        /**
         * CursorDeNovela
         * @description Una fila de `GET /novelas`: dónde va cada novela del directorio de workspaces.
         */
        CursorDeNovela: {
            /** Slug */
            slug: string;
            cursor: components["schemas"]["Cursor"];
        };
        /**
         * EntradaConocimiento
         * @description Misma entrada para `conocimiento` (por personaje) y `conocimiento_lector` (plana).
         */
        EntradaConocimiento: {
            /** Hecho */
            hecho: string;
            /** Desde Capitulo */
            desde_capitulo: number;
            /** Cita */
            cita?: string | null;
        };
        /** EntradaDeFicha */
        EntradaDeFicha: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Detalle */
            detalle: string | null;
            /** Capitulos */
            capitulos: number[];
        };
        /** EntradaDeIndice */
        EntradaDeIndice: {
            /** Capitulo */
            capitulo: number;
            /** Titulo */
            titulo: string;
        };
        /** EntradaTemporal */
        EntradaTemporal: {
            /** Escena */
            escena: string;
            /** Capitulo */
            capitulo: number;
            /** Inicio */
            inicio: string;
            /** Duracion Min */
            duracion_min: number;
            /** Cita */
            cita?: string | null;
        };
        /**
         * Escaleta
         * @description Se valida con `context={"num_capitulos": N}`: la curva tiene un valor por capítulo.
         */
        Escaleta: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Actos */
            actos: components["schemas"]["Acto"][];
            puntos_de_giro: components["schemas"]["PuntosDeGiro"];
            /** Curva Tension Objetivo */
            curva_tension_objetivo: number[];
        };
        /** Estado */
        Estado: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            cursor: components["schemas"]["Cursor"];
            /**
             * Linea Temporal
             * @default []
             */
            linea_temporal: components["schemas"]["EntradaTemporal"][];
            /**
             * Personajes
             * @default {}
             */
            personajes: {
                [key: string]: components["schemas"]["EstadoPersonaje"];
            };
            /**
             * Conocimiento
             * @default {}
             */
            conocimiento: {
                [key: string]: components["schemas"]["EntradaConocimiento"][];
            };
            /**
             * Relaciones
             * @default []
             */
            relaciones: components["schemas"]["Relacion"][];
            /**
             * Objetos
             * @default []
             */
            objetos: components["schemas"]["Objeto"][];
            /**
             * Libro De Hechos
             * @default []
             */
            libro_de_hechos: components["schemas"]["Hecho"][];
            /**
             * Hilos
             * @default []
             */
            hilos: components["schemas"]["Hilo"][];
            /**
             * Pistas
             * @default {}
             */
            pistas: {
                [key: string]: components["schemas"]["EstadoPista"];
            };
            /**
             * Conocimiento Lector
             * @default []
             */
            conocimiento_lector: components["schemas"]["EntradaConocimiento"][];
            /**
             * Tension Real
             * @default []
             */
            tension_real: (number | null)[];
            /**
             * @default {
             *       "palabras_totales": 0,
             *       "desviacion_vs_plan": 0
             *     }
             */
            metricas: components["schemas"]["Metricas"];
        };
        /** EstadoPersonaje */
        EstadoPersonaje: {
            /** Ubicacion */
            ubicacion: string | null;
            /** Estado Fisico */
            estado_fisico: string;
            /** Estado Emocional */
            estado_emocional: string;
            /**
             * Condicion
             * @enum {string}
             */
            condicion: "viva" | "muerta" | "desaparecida";
            /** Objetivo Activo */
            objetivo_activo: string;
            /** Ultima Aparicion */
            ultima_aparicion: number;
        };
        /** EstadoPista */
        EstadoPista: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "plantada" | "pagada" | "pendiente" | "huerfana";
            /** Plantada En */
            plantada_en: number | null;
            /** Pagada En */
            pagada_en: number | null;
        };
        /**
         * FrontmatterCapitulo
         * @description Cabecera de `capitulos/NN.md`. Es una declaración del escritor, no una prueba: `validar`
         *     cuenta las palabras del cuerpo en vez de fiarse de `palabras`.
         */
        FrontmatterCapitulo: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Capitulo */
            capitulo: number;
            /** Titulo */
            titulo: string;
            /** Pov */
            pov: string;
            /** Palabras */
            palabras: number;
            /** Escenas */
            escenas: string[];
            /**
             * Pistas Plantadas
             * @default []
             */
            pistas_plantadas: string[];
            /**
             * Pistas Pagadas
             * @default []
             */
            pistas_pagadas: string[];
            /**
             * Hilos Abiertos
             * @default []
             */
            hilos_abiertos: string[];
            /**
             * Hilos Cerrados
             * @default []
             */
            hilos_cerrados: string[];
            /** Version Canon */
            version_canon: number;
            /** Version Plan */
            version_plan: number;
            /** Run Id */
            run_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hecho */
        Hecho: {
            /** Id */
            id: string;
            /** Texto */
            texto: string;
            /** Capitulo */
            capitulo: number;
            /** Cita */
            cita: string;
        };
        /** Hilo */
        Hilo: {
            /** Id */
            id: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "abierto" | "cerrado";
            /** Abierto En */
            abierto_en: number;
            /** Cerrado En */
            cerrado_en?: number | null;
            /** Descripcion */
            descripcion: string;
        };
        /** InformeDeCostes */
        InformeDeCostes: {
            /** Slug */
            slug: string;
            /** Sesion */
            sesion: string;
            /**
             * Generado
             * Format: date-time
             */
            generado: string;
            /** Pasos */
            pasos: components["schemas"]["ConsumoDePaso"][];
            total: components["schemas"]["TotalDeCostes"];
        };
        /** Lanzamiento */
        Lanzamiento: {
            /** Slug */
            slug: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "en_marcha" | "terminado" | "fallido" | "detenido" | "interrumpido";
            /** Paso */
            paso: string;
            /** Detalle */
            detalle: string;
            /**
             * Actualizado
             * Format: date-time
             */
            actualizado: string;
            /**
             * Detener Pedido
             * @default false
             */
            detener_pedido: boolean;
            /**
             * Registro
             * @default []
             */
            registro: string[];
        };
        /** Libro */
        Libro: {
            /** Titulo */
            titulo: string;
            /** Dedicatoria */
            dedicatoria: string | null;
            /** Capitulos */
            capitulos: components["schemas"]["EntradaDeIndice"][];
            /** Personajes */
            personajes: components["schemas"]["EntradaDeFicha"][];
            /** Lugares */
            lugares: components["schemas"]["EntradaDeFicha"][];
        };
        /**
         * Manifest
         * @description `runs/<run_id>/manifest.json`: lo que permite atribuir un cambio de calidad a un cambio
         *     concreto (validators.md §4.7). Las versiones son hashes de contenido, no números. `fase`
         *     separa el run de arranque —arquitecto y trazador— de los runs de capítulo (spec 0003).
         */
        Manifest: {
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /** Run Id */
            run_id: string;
            /** Capitulo */
            capitulo: number;
            /**
             * Fase
             * @default capitulo
             * @enum {string}
             */
            fase: "arranque" | "capitulo";
            /** Creado */
            creado: string;
            /** Sha Commit */
            sha_commit: string;
            /** Version Recetas */
            version_recetas: string;
            /** Version Canon */
            version_canon: string;
            /** Version Plan */
            version_plan: string;
            /**
             * Sucio
             * @default false
             */
            sucio: boolean;
            /**
             * Hashes Claude
             * @default {}
             */
            hashes_claude: {
                [key: string]: string;
            };
        };
        /** Metricas */
        Metricas: {
            /** Palabras Totales */
            palabras_totales: number;
            /** Desviacion Vs Plan */
            desviacion_vs_plan: number;
        };
        /** Objeto */
        Objeto: {
            /** Id */
            id: string;
            /** Poseedor */
            poseedor: string | null;
            /** Ubicacion */
            ubicacion: string | null;
            /** Capitulo Intro */
            capitulo_intro: number;
            /**
             * Relevancia
             * @enum {string}
             */
            relevancia: "alta" | "media" | "baja";
        };
        /** PalabrasPorCapitulo */
        PalabrasPorCapitulo: {
            /** Objetivo */
            objetivo: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** ParametrosObra */
        ParametrosObra: {
            /** Longitud Total Palabras */
            longitud_total_palabras: number;
            /** Num Capitulos */
            num_capitulos: number;
            palabras_por_capitulo: components["schemas"]["PalabrasPorCapitulo"];
            /**
             * Subgenero
             * @enum {string}
             */
            subgenero: "thriller_psicologico" | "noir" | "domestic_suspense" | "procedural";
            /**
             * Punto De Vista
             * @enum {string}
             */
            punto_de_vista: "primera_persona" | "tercera_limitada" | "multiple" | "narrador_no_fiable";
            /**
             * Tiempo Verbal
             * @enum {string}
             */
            tiempo_verbal: "presente" | "pasado";
            /**
             * Idioma
             * @default es
             */
            idioma: string;
            /**
             * Restricciones Contenido
             * @default []
             */
            restricciones_contenido: string[];
        };
        /** ParametrosSistema */
        ParametrosSistema: {
            /** Modelo Por Agente */
            modelo_por_agente: {
                [key: string]: "opus" | "sonnet" | "haiku" | "inherit";
            };
            /**
             * Temperatura Por Agente
             * @default {}
             */
            temperatura_por_agente: {
                [key: string]: number;
            };
            presupuesto: components["schemas"]["Presupuesto"];
            /**
             * @default {
             *       "max_intentos": 3,
             *       "entrada_del_reintento": "informe_qa"
             *     }
             */
            politica_reintentos: components["schemas"]["PoliticaReintentos"];
            /**
             * Politica Checkpoint
             * @default por_capitulo
             * @constant
             */
            politica_checkpoint: "por_capitulo";
        };
        /**
         * PeticionDeLanzamiento
         * @description Los argumentos de `/novela-nueva`, con los mismos límites que el formulario del panel.
         */
        PeticionDeLanzamiento: {
            /** Slug */
            slug: string;
            /** Idea */
            idea: string;
            /** Capitulos */
            capitulos?: number | null;
            /** Palabras */
            palabras?: number | null;
        };
        /** PoliticaReintentos */
        PoliticaReintentos: {
            /**
             * Max Intentos
             * @default 3
             */
            max_intentos: number;
            /**
             * Entrada Del Reintento
             * @default informe_qa
             * @constant
             */
            entrada_del_reintento: "informe_qa";
        };
        /** Presupuesto */
        Presupuesto: {
            /** Requests Dia */
            requests_dia: number;
            /** Tokens Por Llamada */
            tokens_por_llamada: number;
            /** Tokens Contexto Por Agente */
            tokens_contexto_por_agente: number;
        };
        /**
         * PuntosDeGiro
         * @description Claves fijas, cada una anclada a un capítulo. No es una lista.
         */
        PuntosDeGiro: {
            /** Detonante */
            detonante: number;
            /** Punto Medio */
            punto_medio: number;
            /** Crisis */
            crisis: number;
            /** Climax */
            climax: number;
            /** Resolucion */
            resolucion: number;
        };
        /**
         * Relacion
         * @description Arista de la evolución; `intensidad` es cuantitativa y no es la `tension` del canon.
         */
        Relacion: {
            /** De */
            de: string;
            /** A */
            a: string;
            /** Tipo */
            tipo: string;
            /** Intensidad */
            intensidad: number;
            /** Desde */
            desde: number;
        };
        /** TotalDeCostes */
        TotalDeCostes: {
            /** Llamadas */
            llamadas: number;
            /** Tokens Entrada */
            tokens_entrada: number;
            /** Tokens Salida */
            tokens_salida: number;
            /** Tokens Cache Lectura */
            tokens_cache_lectura: number;
            /** Coste Usd */
            coste_usd: number;
            /** Latencia Media Llamada S */
            latencia_media_llamada_s: number;
            /** Latencia S */
            latencia_s: number;
        };
        /**
         * TramoDeLog
         * @description Líneas completas de `runs/<run_id>/harness.log` desde el byte `desde`. `hasta` es el
         *     siguiente `desde`: el cliente encadena sin que el servidor guarde nada. Sin log, `tamano` 0,
         *     `modificado` None y `hasta` = `desde`. No es documento del workspace: sin schema_version.
         */
        TramoDeLog: {
            /** Desde */
            desde: number;
            /** Hasta */
            hasta: number;
            /** Tamano */
            tamano: number;
            /** Modificado */
            modificado: string | null;
            /** Lineas */
            lineas: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    novelas_novelas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorDeNovela"][];
                };
            };
        };
    };
    estado_novelas__slug__estado_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_novelas__slug__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escaleta_novelas__slug__escaleta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Escaleta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkpoint_novelas__slug__checkpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkpoint"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_novelas__slug__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_novelas__slug__runs__run_id__log_get: {
        parameters: {
            query?: {
                desde?: number;
            };
            header?: never;
            path: {
                run_id: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TramoDeLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manifiesto_novelas__slug__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portada_novelas__slug__portada_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La portada, sin texto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metricas_novelas__slug__metricas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformeDeCostes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indice_novelas__slug__capitulos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontmatterCapitulo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capitulo_novelas__slug__capitulos__n__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                n: number;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    libro_novelas__slug__libro_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Libro"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdf_novelas__slug__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lanzamientos_lanzamientos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lanzamiento"][];
                };
            };
        };
    };
    crear_lanzamientos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionDeLanzamiento"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lanzamiento"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanudar_lanzamientos__slug__reanudar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lanzamiento"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detener_lanzamientos__slug__detener_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lanzamiento"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lanzamiento_lanzamientos__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lanzamiento"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
